// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:fdbeb0c0-a3be-4edb-9440-7cded7bada45",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_BVPznWs9r",
    "aws_user_pools_web_client_id": "2q1mjk22reisk2ppg5svuubiu1"
};


export default awsmobile;
